dist: trusty
sudo: required
language: generic

branches:
  only:
  - master
  - 1.0+mathcomp-1.7.0
  - 1.0+mathcomp-dev

services:
  - docker

env:
  global:
  - NJOBS="2"
  - CONTRIB_NAME="real-closed"
  matrix:
  - COQ_VERSION="8.7"
  - COQ_VERSION="8.8"
  - COQ_VERSION="8.9"
  - COQ_VERSION="dev"


install: |
  # Prepare the COQ container
  docker pull "mathcomp/mathcomp-dev:coq-${COQ_VERSION}"
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} "mathcomp/mathcomp-dev:coq-${COQ_VERSION}"
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    # Using flambda makes sense here as we usually get ~10% faster
    # builds in math-comp.
    eval $(opam env)
    opam update -y
    opam config list
    opam repo list
    opam list
    "
script:
- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex
    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
    eval $(opam env)
    make -j "$NJOBS"
    make install
    "
- docker stop COQ  # optional
- echo -en 'travis_fold:end:script\\r'
